[workspace]
members = [
    "tonic",
    "tonic-build",
    "tonic-health",
    "tonic-reflection",

    # Non-published crates
    "examples",
    "interop",

    # Tests
    "tests/included_service",
    "tests/same_name",
    "tests/wellknown",
    "tests/extern_path/uuid",
    "tests/ambiguous_methods",
    "tests/extern_path/my_application",
    "tests/integration_tests"
]

[replace]
'prost:0.6.1' = { git = "https://github.com/jen20/prost", branch = "jen20/file-descriptor-set" }
'prost-build:0.6.1' = { git = "https://github.com/jen20/prost", branch = "jen20/file-descriptor-set" }
'prost-types:0.6.1' = { git = "https://github.com/jen20/prost", branch = "jen20/file-descriptor-set" }
