[graph]
all-features = true
exclude = ["examples"]

[advisories]
ignore = [
  { id = "RUSTSEC-2024-0436", reason = "paste crate is unmaintained. aws-lc-rs, aws-lc-sys and compression test depend on it." },
]

[bans]
multiple-versions = "deny"
deny = [
    # color-backtrace is nice but brings in too many dependencies and that are often outdated, so not worth it for us.
    { crate = "color-backtrace" },

    # dirs crate has a lot of dependencies and there are better alternatives
    { crate = "dirs" },
    { crate = "dirs-sys" },

    # deprecated
    { crate = "quickersort" },

    # term is not fully maintained, and termcolor is replacing it
    { crate = "term" },
]
skip = [
    { crate = "getrandom@0.2.15", reason = "quickcheck depends on rand which depends on it" },
    { crate = "wasi@0.11.0+wasi-snapshot-preview1", reason = "quickcheck depends on rand which depends on it" },
    { crate = "itertools@0.12.1", reason = "aws-lc-sys depends on bindgen which depends on it" },
    { crate = "unicode-width@0.1.14", reason = "protox depends on miette wich depends on it" },
    { crate = "rustix@0.38.44", reason = "aws-lc-sys depends on bindgen which depends on it" },
    { crate = "linux-raw-sys@0.4.15", reason = "rustix 0.38.44 depends on it" },
]
skip-tree = [
    { crate = "windows-sys" },
    { crate = "hermit-abi" },
]

[licenses]
version = 2
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.92
allow = [
    "Apache-2.0",
    "ISC",
    "MIT",
    "OpenSSL",
    "Unicode-3.0",
    "MPL-2.0",
    "BSD-3-Clause",
]

[[licenses.clarify]]
crate = "ring"
# SPDX considers OpenSSL to encompass both the OpenSSL and SSLeay licenses
# https://spdx.org/licenses/OpenSSL.html
# ISC - Both BoringSSL and ring use this for their new files
# MIT - "Files in third_party/ have their own licenses, as described therein. The MIT
# license, for third_party/fiat, which, unlike other third_party directories, is
# compiled into non-test libraries, is included below."
# OpenSSL - Obviously
expression = "ISC AND MIT AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]
