[graph]
all-features = true
exclude = ["examples"]

[advisories]
ignore = [
  { id = "RUSTSEC-2024-0436", reason = "paste crate is unmaintained. aws-lc-rs, aws-lc-sys and compression test depend on it." },
]

[bans]
multiple-versions = "deny"
deny = [
    # color-backtrace is nice but brings in too many dependencies and that are often outdated, so not worth it for us.
    { crate = "color-backtrace" },

    # dirs crate has a lot of dependencies and there are better alternatives
    { crate = "dirs" },
    { crate = "dirs-sys" },

    # deprecated
    { crate = "quickersort" },

    # term is not fully maintained, and termcolor is replacing it
    { crate = "term" },
]
skip = [
    { crate = "getrandom@0.2.15", reason = "quickcheck depends on rand which depends on it" },
    { crate = "wasi@0.11.0+wasi-snapshot-preview1", reason = "quickcheck depends on rand which depends on it" },
    { crate = "itertools@0.12.1", reason = "aws-lc-sys depends on bindgen which depends on it" },
    { crate = "unicode-width@0.1.14", reason = "protox depends on miette wich depends on it" },
    { crate = "rustix@0.38.44", reason = "aws-lc-sys depends on bindgen which depends on it" },
    { crate = "linux-raw-sys@0.4.15", reason = "rustix 0.38.44 depends on it" },
]
skip-tree = [
    { crate = "windows-sys" },
    { crate = "hermit-abi" },
]

[licenses]
version = 2
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.92
allow = [
    "Apache-2.0",
    "ISC",
    "MIT",
    "BSD-3-Clause",
]
exceptions = [
    { allow = ["OpenSSL"], name = "aws-lc-sys" },
    { allow = ["Unicode-3.0"], name = "unicode-ident" },
    { allow = ["MPL-2.0"], name = "webpki-roots" },
]
