[package]
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
categories = ["web-programming", "network-programming", "asynchronous"]
description = """
A collection of useful protobuf types that can be used with `tonic`.
"""
documentation = "https://docs.rs/tonic-types/0.4.0/tonic-types/"
edition = "2018"
homepage = "https://github.com/hyperium/tonic"
keywords = ["rpc", "grpc", "protobuf"]
license = "MIT"
name = "tonic-types"
readme = "../README.md"
repository = "https://github.com/hyperium/tonic"
version = "0.4.0"

[dependencies]
prost = "0.9"
prost-types = "0.9"

[build-dependencies]
prost-build = "0.9"
