[package]
authors = [
  "Lucio Franco <luciofranco14@gmail.com>",
  "Rafael Lemos <flemos.rafael.dev@gmail.com>"
]
categories = ["web-programming", "network-programming", "asynchronous"]
description = """
A collection of useful protobuf types that can be used with `tonic`.
"""
documentation = "https://docs.rs/tonic-types/0.10.2"
edition = "2021"
homepage = "https://github.com/hyperium/tonic"
keywords = ["rpc", "grpc", "protobuf"]
license = "MIT"
name = "tonic-types"
readme = "README.md"
repository = "https://github.com/hyperium/tonic"
version = "0.10.2"

[dependencies]
prost = "0.12"
prost-types = "0.12"
tonic = {version = "0.10", path = "../tonic", default-features = false}
