[package]
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
categories = ["network-programming", "asynchronous"]
description = """
Codegen module of `tonic` gRPC implementation.
"""
documentation = "https://docs.rs/tonic-build/0.6.2/tonic_build/"
edition = "2018"
homepage = "https://github.com/hyperium/tonic"
keywords = ["rpc", "grpc", "async", "codegen", "protobuf"]
license = "MIT"
name = "tonic-build"
readme = "README.md"
repository = "https://github.com/hyperium/tonic"
version = "0.6.2"

[dependencies]
proc-macro2 = "1.0"
prost-build = {version = "0.9", optional = true}
quote = "1.0"
syn = "1.0"

[features]
compression = []
default = ["transport", "rustfmt", "prost"]
prost = ["prost-build"]
rustfmt = []
transport = []

[package.metadata.docs.rs]
all-features = true
