[package]
name = "tonic-build"
version = "0.1.0"
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost-build = "0.5"
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"


[features]
default = ["transport"]
rustfmt = []
transport = []
