[package]
name = "tonic-xds"
version = "0.1.0-alpha.1"
edition = "2021"
rust-version.workspace = true

[dependencies]
tonic = "0.14"
http = "1"
tower = { version = "0.5", default-features = false, features = ["discover"] }
envoy-types = "0.7"
dashmap = "6.1"
thiserror = "2.0.17"
futures = "0.3.31"

[lints]
workspace = true

[build-dependencies]
tonic-prost-build = "0.14"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
tonic = { version = "0.14", features = [ "server", "channel", "tls-ring" ] }
prost = "0.14"
tonic-prost = "0.14"
anyhow = "1"
tokio-stream = "0.1"
